### ISSUE TITLE
Centered, fixed width?

### ISSUE THREAD

**Issue by intermedion** [mourner/dead-simple-grid#1]
What changes are needed to make this grid work for a centered, fixed width layout and still be responsive, mobile-first?

**Comment by mourner** [comment]
You need your container to have `max-width: <...>` and `margin: 0 auto` set. This way it will be centered and have a fixed width after a particular browser width, and flow full-width otherwise.

**Comment by intermedion** [comment]
Indeed, thank you; also, in the given example the .content width has to be set to 100% in the media queries (or just removed), otherwise it does not quite work, the layout may be offset to the left.
