### ISSUE TITLE
.row:after?

### ISSUE THREAD

**Issue by rjbudzynski** [mourner/dead-simple-grid#9]
Your grid.css has a selector `.row:after`. Now, I am no css expert, but I looked up all the docs I could and all I could find pointed to `.row::after` being the correct syntax (a double colon, not single). What's more, I tried to follow the guidance in your README.md, and nothing of it worked (in a current Chrome), until I changed that colon to a double-colon.
Now, for some reason, your demo on githib pages *does* work as-is. In the same browser. Go figure.

**Comment by mourner** [comment]
See https://css-tricks.com/almanac/selectors/a/after-and-before/#article-header-id-0
